/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnalysisCard: typeof import('./src/components/costAnalysis/analysisCard.vue')['default']
    BarBox: typeof import('./src/components/barBox/barBox.vue')['default']
    Border: typeof import('./src/components/border/border.vue')['default']
    Card: typeof import('./src/components/card/card.vue')['default']
    Chart: typeof import('./src/components/chart/chart.vue')['default']
    InfoCard: typeof import('./src/components/infoCard/infoCard.vue')['default']
    InfoCardSingle: typeof import('./src/components/infoCard/infoCard-single.vue')['default']
    ItemTitle: typeof import('./src/components/itemTitle/itemTitle.vue')['default']
    Legends: typeof import('./src/components/legends/legends.vue')['default']
    LineLegend: typeof import('./src/components/legends/lineLegend.vue')['default']
    MapChart: typeof import('./src/components/maps/mapChart.vue')['default']
    MapDialog: typeof import('./src/components/maps/mapDialog.vue')['default']
    MyDialog: typeof import('./src/components/myDialog/myDialog.vue')['default']
    PageHead: typeof import('./src/components/pageHead/pageHead.vue')['default']
    Progress: typeof import('./src/components/progress/progress.vue')['default']
    Rank: typeof import('./src/components/rank/rank.vue')['default']
    RankBar: typeof import('./src/components/rank/rankBar.vue')['default']
    RankItem: typeof import('./src/components/rank/rankItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquareLegend: typeof import('./src/components/legends/squareLegend.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
