export default [
	{
		title: '白云污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				// "告警状态 1：未处理 2：已处理 3：处理中"
		level: 1, 				// "告警级别 1：低 2：中 3：高"
		type: 1,				// "告警类别 1：水质告警 2：设备告警,3：库存告警，4：指标告警，5：断电告警，6：系统告警"
		facName: '白云污水厂',	// 告警厂站
		handleTime: '',			// 处理事件
		handlePeople: '',		// 处理人
		handlePeopleID: '',		// 处理人ID
	},
	{
		title: '湛江污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '湛江污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '清远污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '清远污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '荆州污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '荆州污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '长沙污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '长沙污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '岳阳污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '岳阳污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '武汉污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '武汉污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '荆门污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '荆门污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '常德污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '常德污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
	{
		title: '百色污水厂掉线',
		content: '',
		time: '07-22 17:22',
		status: 1,				
		level: 1, 				
		type: 1,				
		facName: '百色污水厂',	
		handleTime: '',			
		handlePeople: '',		
		handlePeopleID: '',		
	},
]